INSERT INTO 
    question 
VALUES 
    (1, "FUVEST", 2018, "Biology", "a-surdez-é-geneticamente-heterogênea:-pode-ser-causada-por-mutações", "A surdez é geneticamente heterogênea: pode ser causada por mutações em diferentes genes, localizados nos autossomos ou no cromossomo X ou, ainda, por mutações em genes mitocondriais. Os heredogramas representam quatro famílias, em que ocorrem pessoas com surdez. A(s) família(s) em que o padrão de herança permite afastar a possibilidade de que a surdez tenha herança mitocondrial é(são) apenas"),
    (2, "FUVEST", 2022, "Physics", "um-bom-café-deve-ser-preparado-a-uma-temperatura-pouco", "Um bom café deve ser preparado a uma temperatura pouco acima de 80 ºC. Para evitar queimaduras na boca, deve ser consumido a uma temperatura mais baixa. Uma xícara contém 60 mL de café a uma temperatura de 80ºC. Qual a quantidade de leite gelado (a uma temperatura de 5o C) deve ser misturada ao café para que a temperatura final do café com leite seja de 65 ºC?"),
    (3, "UNICAMP", 2022, "Geography", "a-linha-internacional-de-mudança-de-data-é-uma-linha", "A linha internacional de mudança de data é uma linha imaginária posicionada próximo ao meridiano de 180º ou diametralmente oposta ao meridiano de Greenwich, cortando o Oceano Pacífico. Uma característica dessa linha está na sua forma irregular, o que evita que um país tenha a mesma hora e dias diferentes, conforme ilustra a figura a seguir. A partir da leitura do enunciado e da análise da ilustração, podemos concluir que"),
    (4, "UNESP", 2022, "Portuguese", "examine-o-cartum-de-pietro-soldi,-publicado-em-sua-conta", "Examine o cartum de Pietro Soldi, publicado em sua conta do Instagram em 11.09.2019. Depreende-se do cartum que o motorista"),
    (5, "UFRGS", 2021, "Mathematics", "conidere-o-padrão-de-construção-de-triângulos-com-palitos-representado", "Conidere o padrão de construção de triângulos com palitos, representado nas figuras abaixo. Na etapa n, serão utilizados 245 palitos. Nessas condições, n é igual a");

